[project]
name = "lstm-sgarch-rr"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26",
    "pandas>=2.2",
    "pandas-stubs>=3.0.0.260204",
    "scikit-learn>=1.4",
    "scikit-learn-stubs>=0.0.3",
    "tqdm>=4.67.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.7",
    "matplotlib>=3.10.9",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
]
linux-gpu = [
    "arch>=7.2.0; platform_system == 'Linux'",
    "setuptools>=70.0.0,<82.0.0; platform_system == 'Linux'",
    "tensorboard>=2.20.0; platform_system == 'Linux'",
    "tensorflow[and-cuda]>=2.21.0; platform_system == 'Linux'",
]
